# Generated by Django 4.0.5 on 2022-06-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bd',
            options={'verbose_name': 'Публикации', 'verbose_name_plural': 'Публикации'},
        ),
    ]
