# Generated by Django 4.0.5 on 2022-06-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_bd_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='contents',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
