# Generated by Django 4.0.5 on 2022-06-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_bd_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bd',
            old_name='Название',
            new_name='title',
        ),
    ]
