# Generated by Django 4.0.5 on 2022-06-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_название_bd_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
